version: "3.7"
services:
  web: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
    - ./:/var/www
    - ./conf/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
    - project

  php:
    image: php:7.3-fpm
    container_name: php-fpm
    volumes:
    - ./:/var/www
    networks:
      - project
  
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./conf/mysql:/docker-entrypoint-initdb.d
    networks:
      - project


networks:
  project:
    driver: bridge
